export function MAKEINTRESOURCE(id: number): bigint {
  return BigInt(id & 0xffff);
}

export const IDC_ARROW = MAKEINTRESOURCE(32512);
export const IDC_IBEAM = MAKEINTRESOURCE(32513);
export const IDC_WAIT = MAKEINTRESOURCE(32514);
export const IDC_CROSS = MAKEINTRESOURCE(32515);
export const IDC_UPARROW = MAKEINTRESOURCE(32516);
export const IDC_SIZE = MAKEINTRESOURCE(32640);
export const IDC_ICON = MAKEINTRESOURCE(32641);
export const IDC_SIZENWSE = MAKEINTRESOURCE(32642);
export const IDC_SIZENESW = MAKEINTRESOURCE(32643);
export const IDC_SIZEWE = MAKEINTRESOURCE(32644);
export const IDC_SIZENS = MAKEINTRESOURCE(32645);
export const IDC_SIZEALL = MAKEINTRESOURCE(32646);
export const IDC_NO = MAKEINTRESOURCE(32648);
export const IDC_HAND = MAKEINTRESOURCE(32649);
export const IDC_APPSTARTING = MAKEINTRESOURCE(32650);
export const IDC_HELP = MAKEINTRESOURCE(32651);
export const IDC_PIN = MAKEINTRESOURCE(32671);
export const IDC_PERSON = MAKEINTRESOURCE(32672);
